# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 587)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setTabsClosable(True)
        self.tabs.setObjectName("tabs")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuBacktest = QtWidgets.QMenu(self.menubar)
        self.menuBacktest.setObjectName("menuBacktest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenTrades = QtWidgets.QAction(MainWindow)
        self.actionOpenTrades.setObjectName("actionOpenTrades")
        self.actionNew_strategy = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/icons/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_strategy.setIcon(icon)
        self.actionNew_strategy.setObjectName("actionNew_strategy")
        self.actionOpen_strategy = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_strategy.setIcon(icon1)
        self.actionOpen_strategy.setObjectName("actionOpen_strategy")
        self.actionExecute = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/icons/execute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExecute.setIcon(icon2)
        self.actionExecute.setObjectName("actionExecute")
        self.actionSave_strategy = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_strategy.setIcon(icon3)
        self.actionSave_strategy.setObjectName("actionSave_strategy")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuFile.addAction(self.actionNew_strategy)
        self.menuFile.addAction(self.actionOpen_strategy)
        self.menuFile.addAction(self.actionSave_strategy)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menuBacktest.addAction(self.actionExecute)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBacktest.menuAction())
        self.toolBar.addAction(self.actionNew_strategy)
        self.toolBar.addAction(self.actionOpen_strategy)
        self.toolBar.addAction(self.actionSave_strategy)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExecute)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(-1)
        self.actionOpen_strategy.triggered.connect(MainWindow.openStrategy)
        self.tabs.tabCloseRequested['int'].connect(MainWindow.tabCloseRequested)
        self.actionNew_strategy.triggered.connect(MainWindow.newStrategy)
        self.actionExecute.triggered.connect(MainWindow.executeStrategy)
        self.actionSave_strategy.triggered.connect(MainWindow.saveStrategy)
        self.actionSave_as.triggered.connect(MainWindow.saveStrategyAs)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nailab"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuBacktest.setTitle(_translate("MainWindow", "Backtest"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpenTrades.setText(_translate("MainWindow", "Open..."))
        self.actionNew_strategy.setText(_translate("MainWindow", "New strategy"))
        self.actionNew_strategy.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen_strategy.setText(_translate("MainWindow", "Open strategy"))
        self.actionOpen_strategy.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExecute.setText(_translate("MainWindow", "Execute"))
        self.actionSave_strategy.setText(_translate("MainWindow", "Save strategy"))
        self.actionSave_strategy.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))

import nailab_rc
